/*****************************************************************************
* Model: display_test_qpn.qm
* File:  ./display_test.c
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/* @(/1/3/1) ...............................................................*/
#include "qpn_port.h"
#include "bsp_.h"
#include "display_test.h"

/*Q_DEFINE_THIS_FILE*/

#define SCROLLING_TOUT BSP_TICKS_PER_SEC
#define IDLE_TOUT BSP_TICKS_PER_SEC

/* Pelican class declaration -----------------------------------------------*/
/* @(/1/0) .................................................................*/
typedef struct DisplayTag {
/* protected: */
    QMActive super;
} Display;

/* protected: */
static QState Display_initial(Display * const me);
static QState Display_IDLE  (Display * const me);
static QState Display_IDLE_e(Display * const me);
static QState Display_IDLE_x(Display * const me);
static QMState const Display_IDLE_s = {
    (QMState const *)0,
    Q_STATE_CAST(&Display_IDLE),
    Q_ACTION_CAST(&Display_IDLE_x)
};
static QState Display_SCROLLING  (Display * const me);
static QState Display_SCROLLING_e(Display * const me);
static QState Display_SCROLLING_x(Display * const me);
static QMState const Display_SCROLLING_s = {
    (QMState const *)0,
    Q_STATE_CAST(&Display_SCROLLING),
    Q_ACTION_CAST(&Display_SCROLLING_x)
};


/* Global objects ----------------------------------------------------------*/
Display AO_Display;     /* the single instance of the Display active object */

/* Blink class definition --------------------------------------------------*/
/* @(/1/2) .................................................................*/
void Display_ctor(void) {
    QMActive_ctor(&AO_Display.super, Q_STATE_CAST(&Display_initial));
}
/* @(/1/0) .................................................................*/
/* @(/1/0/0) ...............................................................*/
/* @(/1/0/0/0) */
static QState Display_initial(Display * const me) {
    static QActionHandler const act_[] = {
        Q_ACTION_CAST(&Display_IDLE_e),
        Q_ACTION_CAST(0)
    };
    return QM_INITIAL(&Display_IDLE_s, &act_[0]);
}
/* @(/1/0/0/1) .............................................................*/
static QState Display_IDLE_e(Display * const me) {
    BSP_ledOff();
    QActive_arm((QActive *)me, IDLE_TOUT);
    return QM_ENTRY(&Display_IDLE_s);
}
static QState Display_IDLE_x(Display * const me) {
    QActive_disarm((QActive *)me);
    return QM_EXIT(&Display_IDLE_s);
}
static QState Display_IDLE(Display * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /* @(/1/0/0/1/0) */
        case Q_TIMEOUT_SIG: {
            static QActionHandler const act_[] = {
                Q_ACTION_CAST(&Display_IDLE_x),
                Q_ACTION_CAST(&Display_SCROLLING_e),
                Q_ACTION_CAST(0)
            };
            status_ = QM_TRAN(&Display_SCROLLING_s, &act_[0]);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}
/* @(/1/0/0/2) .............................................................*/
static QState Display_SCROLLING_e(Display * const me) {
    BSP_ledOn();
    BSP_drawPicture();
    QActive_arm((QActive *)me, SCROLLING_TOUT);
    return QM_ENTRY(&Display_SCROLLING_s);
}
static QState Display_SCROLLING_x(Display * const me) {
    QActive_disarm((QActive *)me);
    return QM_EXIT(&Display_SCROLLING_s);
}
static QState Display_SCROLLING(Display * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /* @(/1/0/0/2/0) */
        case Q_TIMEOUT_SIG: {
            static QActionHandler const act_[] = {
                Q_ACTION_CAST(&Display_SCROLLING_x),
                Q_ACTION_CAST(&Display_IDLE_e),
                Q_ACTION_CAST(0)
            };
            status_ = QM_TRAN(&Display_IDLE_s, &act_[0]);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

