/*****************************************************************************
* Model: blink_qpn.qm
* File:  ./blink.h
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/* @(/1/3/0) ...............................................................*/
#ifndef __BLINK_H__
#define __BLINK_H__

// active objects ................................................*/
/* @(/1/2) .................................................................*/
void Blink_ctor(void);


extern struct BlinkTag AO_Blink;

#endif /* __BLINK_H__ */
