/*****************************************************************************
* Model: blink_qpn.qm
* File:  ./blink.c
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/* @(/1/3/1) ...............................................................*/
#include "qpn_port.h"
#include "bsp_.h"
#include "blink.h"

/*Q_DEFINE_THIS_FILE*/

#define BLINK_ON_TOUT BSP_TICKS_PER_SEC/5
#define BLINK_OFF_TOUT BSP_TICKS_PER_SEC

/* Pelican class declaration -----------------------------------------------*/
/* @(/1/0) .................................................................*/
typedef struct BlinkTag {
/* protected: */
    QMActive super;
} Blink;

/* protected: */
static QState Blink_initial(Blink * const me);
static QState Blink_ON  (Blink * const me);
static QState Blink_ON_e(Blink * const me);
static QState Blink_ON_x(Blink * const me);
static QMState const Blink_ON_s = {
    (QMState const *)0,
    Q_STATE_CAST(&Blink_ON),
    Q_ACTION_CAST(&Blink_ON_x)
};
static QState Blink_OFF  (Blink * const me);
static QState Blink_OFF_e(Blink * const me);
static QState Blink_OFF_x(Blink * const me);
static QMState const Blink_OFF_s = {
    (QMState const *)0,
    Q_STATE_CAST(&Blink_OFF),
    Q_ACTION_CAST(&Blink_OFF_x)
};


/* Global objects ----------------------------------------------------------*/
Blink AO_Blink;           /* the single instance of the Blink active object */

/* Blink class definition --------------------------------------------------*/
/* @(/1/2) .................................................................*/
void Blink_ctor(void) {
    QMActive_ctor(&AO_Blink.super, Q_STATE_CAST(&Blink_initial));
}
/* @(/1/0) .................................................................*/
/* @(/1/0/0) ...............................................................*/
/* @(/1/0/0/0) */
static QState Blink_initial(Blink * const me) {
    static QActionHandler const act_[] = {
        Q_ACTION_CAST(&Blink_ON_e),
        Q_ACTION_CAST(0)
    };
    return QM_INITIAL(&Blink_ON_s, &act_[0]);
}
/* @(/1/0/0/1) .............................................................*/
static QState Blink_ON_e(Blink * const me) {
    BSP_ledOn();
    QActive_arm((QActive *)me, BLINK_ON_TOUT);
    return QM_ENTRY(&Blink_ON_s);
}
static QState Blink_ON_x(Blink * const me) {
    QActive_disarm((QActive *)me);
    return QM_EXIT(&Blink_ON_s);
}
static QState Blink_ON(Blink * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /* @(/1/0/0/1/0) */
        case Q_TIMEOUT_SIG: {
            static QActionHandler const act_[] = {
                Q_ACTION_CAST(&Blink_ON_x),
                Q_ACTION_CAST(&Blink_OFF_e),
                Q_ACTION_CAST(0)
            };
            status_ = QM_TRAN(&Blink_OFF_s, &act_[0]);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}
/* @(/1/0/0/2) .............................................................*/
static QState Blink_OFF_e(Blink * const me) {
    BSP_ledOff();
    QActive_arm((QActive *)me, BLINK_OFF_TOUT);
    return QM_ENTRY(&Blink_OFF_s);
}
static QState Blink_OFF_x(Blink * const me) {
    QActive_disarm((QActive *)me);
    return QM_EXIT(&Blink_OFF_s);
}
static QState Blink_OFF(Blink * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /* @(/1/0/0/2/0) */
        case Q_TIMEOUT_SIG: {
            static QActionHandler const act_[] = {
                Q_ACTION_CAST(&Blink_OFF_x),
                Q_ACTION_CAST(&Blink_ON_e),
                Q_ACTION_CAST(0)
            };
            status_ = QM_TRAN(&Blink_ON_s, &act_[0]);
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}

